return {
    -- Import plugin configurations
    require("rpreziosi.lazy.treesitter"),
    require("rpreziosi.lazy.telescope"),
    require("rpreziosi.lazy.gitsigns"),
    require("rpreziosi.lazy.copilot"),
    require("rpreziosi.lazy.sf"),
    require("rpreziosi.lazy.lualine"),
    require("rpreziosi.lazy.fugitive"),
    require("rpreziosi.lazy.diffview"),
    require("rpreziosi.lazy.lspconfig"),
    require("rpreziosi.lazy.cmp"),
    require("rpreziosi.lazy.whichkey"),
    require("rpreziosi.lazy.oil"),
    require("rpreziosi.lazy.plant"),
    require("rpreziosi.lazy.tmuxnavigator"),
    require("rpreziosi.lazy.indentBlackLine"),
    require("rpreziosi.lazy.comment"),
    require("rpreziosi.lazy.nvimlint"),
    require("rpreziosi.lazy.avante"),
    require("rpreziosi.lazy.flash"),
    require("rpreziosi.lazy.undotree"),
    require("rpreziosi.lazy.themes"),
    require("rpreziosi.lazy.mini"),
}
